name: time_tracking
description: A new Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.17.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  auto_route: ^3.2.1
  dartz: ^0.10.1
  easy_localization: ^3.0.0
  flutter_bloc: ^8.0.1
  get_it: ^7.2.0
  flutter_gen: ^4.1.5
  flutter_screenutil: ^5.1.0
  injectable: ^1.5.3
  internet_connection_checker: ^0.0.1+3
  intl: ^0.17.0
  json_annotation: ^4.4.0
  jwt_decoder: ^2.0.1
  retrofit: ^3.0.1
  shared_preferences: ^2.0.12
  logger: ^1.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0
  auto_route_generator: ^3.2.1
  retrofit_generator: ^4.0.1
  build_runner: ^2.1.7
  flutter_gen_runner: ^4.1.5
  injectable_generator: ^1.5.3
  json_serializable: ^6.1.4
#  mockito: ^5.1.0
#  http_mock_adapter: ^0.3.2
  rename: ^2.0.1
  flutter_launcher_icons: ^0.9.2


flutter:

  uses-material-design: true

  assets:
    - assets/translations/
    - assets/images/
    - assets/icons/general/
    - assets/icons/task/


  fonts:
    - family: Butler
      fonts:
        - asset: assets/fonts/Butler_Light.ttf
        - asset: assets/fonts/Butler_Regular.ttf
        - asset: assets/fonts/Butler_Bold.ttf

    - family: IBMPlexSans
      fonts:
        - asset: assets/fonts/IBMPlexSans-Light.ttf
        - asset: assets/fonts/IBMPlexSans-Regular.ttf
        - asset: assets/fonts/IBMPlexSans-Bold.ttf
